---
abstract: 'Perl extension for performing fuzzy comparisons between bibliographic citations'
author:
  - 'David Bourget'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Biblio-Citation-Compare
no_index:
  directory:
    - t
    - inc
requires:
  HTML::Parser: 2.25
  Test::More: 0.96
  Text::LevenshteinXS: 0.03
  Text::Names: 0.19
version: 0.21
