--- #YAML:1.0
name:               Biblio-Citation-Compare
version:            0.04
abstract:           Perl extension for performing fuzzy comparisons between bibliographic citations
author:
    - David Bourget
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Parser:         2.25
    Test::More:           0.96
    Text::LevenshteinXS:  0.03
    Text::Names:          0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
